# Generated by Django 2.2.24 on 2023-03-20 16:18

from django.db import migrations

def new_buildings_default(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.filter(construction_year__gte=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20230320_1917'),
    ]

    operations = [
        migrations.RunPython(new_buildings_default),
    ]
