# Generated by Django 2.2.24 on 2023-03-19 09:19

from django.db import migrations


def new_buildings_default(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.filter(construction_year__gte=2015):
        flat.new_building = True
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20230319_1358'),
    ]

    operations = [
        migrations.RunPython(new_buildings_default),
    ]
