# Generated by Django 2.2.24 on 2023-03-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(related_name='flats_by_owner', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
