# Generated by Django 2.2.24 on 2023-03-26 09:55

from django.db import migrations



def copy_flats_to_owners (apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner_name=flat.owner, owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230325_2051'),
    ]

    operations = [
        migrations.RunPython(copy_flats_to_owners)
    ]
