# Generated by Django 2.2.24 on 2023-03-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230326_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(db_index=True, related_name='owned_flats', to='property.Owner', verbose_name='Квартиры в собственности'),
        ),
    ]
