# Generated by Django 2.2.24 on 2023-03-26 17:08

from django.db import migrations


def correspondent_flats_owners (apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")
    for flat in Flat.objects.all():
        owner_name = flat.owner
        owners_phonenumber = flat.owners_phonenumber
        owner = Owner.objects.get_or_create(owner_name=owner_name,
                                                    owners_phonenumber=owners_phonenumber)

        # owner[0].flats.set(owner[0])

        owner[0].flats.add(flat)
        owner[0].save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20230326_1603'),
    ]

    operations = [
        migrations.RunPython(correspondent_flats_owners)
    ]
