# Generated by Django 2.2.24 on 2023-04-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_auto_20230421_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint',
            new_name='flat',
        ),
    ]
